color0 #514537
color1 #ffb4ab
color2 #fdba5a
color3 #e5c093
color4 #bfcf6c
color5 #fdba5a
color6 #e5c093
color7 #ece0d5
color8 #9e8e7d
color9 #ffb4ab
color10 #fdba5a
color11 #e5c093
color12 #bfcf6c
color13 #fdba5a
color14 #e5c093
color15 #ece0d5

cursor                #ece0d5
cursor_text_color     #18120c
background            #18120c
foreground            #ece0d5
selection_foreground  #d5c4b1
selection_background  #514537
active_border_color   #fdba5a
inactive_border_color #514537
url_color             #fdba5a

active_tab_foreground   #452b00
active_tab_background   #fdba5a
inactive_tab_foreground #d5c4b1
inactive_tab_background #514537
cursor_trail_color      #d5c4b1
