# ── Font ──────────────────────────────────────
font_size 10.0
# font_family JetBrainsMono Nerd Font

# ── Transparency ──────────────────────────────
background_opacity 0.2899

dynamic_background_opacity yes
background_blur 1

# ── Noctalia dynamic theming (enable later) ───
 include themes/noctalia.confinclude themes/noctalia.conf
include themes/noctalia.conf


